### PR TITLE
Failing spec

### PR DESCRIPTION
**Pull request by krzysiek1507**
```ruby
Failure/Error: expect(evaljs("Routes.foo_all_path()")).to eq(routes.foo_all_path(:format => "json"))
    expected: "/other_optional.json"
         got: "/other_optional/.json"
```

### CODE REVIEW

**Comment by le0pard** [comment]
Hello, @krzysiek1507 Please, rebase from latest master you PR, because test failing.

**Comment by krzysiek1507** [comment]
@le0pard, rebased

**Comment by le0pard** [comment]
@krzysiek1507 looks like this test not pass.

**Comment by krzysiek1507** [comment]
@le0pard I added this PR to show this test is failing. Sorry, but I don't know how to fix it. ;)

**Comment by krzysiek1507** [comment]
@le0pard have you got any idea how to fix it?

**Comment by bogdan** [comment]
@krzysiek1507 why does it fail for you? It passes on CI and on my local machine. Which version of Rails did you use?

**Comment by le0pard** [comment]
@krzysiek1507 I will look later, with optional params always tricky problems.
@bogdan Look here: https://travis-ci.org/railsware/js-routes/builds/131826937

**Comment by bogdan** [comment]
@le0pard so the build for this PR is failing while master passes. I have no idea what you are trying to do.

**Comment by le0pard** [comment]
@bogdan krzysiek1507 created this PR with failed test, but not with solution how to fix this. To show it for us - https://github.com/railsware/js-routes/pull/191#issuecomment-220776312

**Comment by bogdan** [comment]
Ok, got it.

2016-06-02 12:11 GMT+03:00 Alexey Vasiliev <notifications@github.com>:

> @bogdan <https://github.com/bogdan> krzysiek1507 created this PR with
> failed test, but not with solution how to fix this. To show it for us - #191
> (comment)
> <https://github.com/railsware/js-routes/pull/191#issuecomment-220776312>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/railsware/js-routes/pull/191#issuecomment-223237479>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAHeRH1mDZ61rg6CnlJ6tuvGJXdDDG66ks5qHp41gaJpZM4IgrPi>
> .
>



-- 
Bogdan Gusiev.
agresso@gmail.com

**Comment by krzysiek1507** [comment]
@bogdan @le0pard new release? ;)

**Comment by bogdan** [comment]
Enjoy 1.2.6

**Comment by krzysiek1507** [comment]
Thanks ;)

**Pull request merged**
