### PR TITLE
Default config.prefix to the Rails relative URL root and note details in the README

### PR DESCRIPTION
**Pull request by tknarr**

### CODE REVIEW

**Comment by bogdan** [comment]
Is the ENV var reflected in rails setting `relative_url_path`? If so, I think we can make a default `prefix` option to qual to `relative_url_path` rails config option.

**Comment by tknarr** [comment]
Yes, it is. From the discussions under the Rails issues it seems like it's only purpose is to get that setting correct during precompilation.

**Comment by bogdan** [comment]
So, lets just do that.

**Comment by tknarr** [comment]
OK, I'll add that to this pull request.

**Comment by tknarr** [comment]
I'm just going to start a different pull request after I set things up correctly on my end.

**Pull request closed without merging**
