### PR TITLE
Use flat_map rather than map.flatten

### PR DESCRIPTION
**Pull request by glittershark**
This is a small performance and readability boost.

### CODE REVIEW

**Comment by le0pard** [comment]
Agree - http://gistflow.com/posts/578-use-flat_map-instead-of-map-flatten @glittershark, can you add this to CHANGELOG.md?

**Comment by glittershark** [comment]
Sure! Would you rather that in a separate commit or squashed into one?

**Comment by le0pard** [comment]
"squashed into one" please :+1:

**Comment by glittershark** [comment]
done!

**Comment by le0pard** [comment]
Thanks!

**Pull request merged**
