### PR TITLE
fall back url to path if hostname is missing

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by le0pard** [comment]
@krzysiek1507 can we also change this one:

```
has_location: ->
     typeof window != 'undefined' && typeof window.location != 'undefined'
```

to better version:

```
has_location: -> window? and window.location?
```

in this PR?

**Comment by krzysiek1507** [comment]
@le0pard it's out of scope (just refactoring) so I can create a new PR for it, but if you prefer to have it in one PR, I can do it

**Comment by krzysiek1507** [comment]
```js
has_location: -> window? and window.location?
```
=> 
```js
has_location: function() {
  return (typeof window !== "undefined" && window !== null) && (window.location != null);
}
```
OR
```js
has_location2: -> window?.location?
```
=>
```js
has_location2: function() {
  return (typeof window !== "undefined" && window !== null ? window.location : void 0) != null;
}
```

**Comment by le0pard** [comment]
Both good, because valid checks.

**Comment by krzysiek1507** [comment]
@le0pard pushed. Unfortunately, I can see any specs for it.

**Comment by le0pard** [comment]
@krzysiek1507 waiting for @bogdan 👍

**Comment by krzysiek1507** [comment]
Thanks!

It would be great if you could release a new version with this change. Unfortunately, I'm blocked by this. :(

**Pull request merged**
