### PR TITLE
changed export variable to request another object to avoid conflicts with other libraries

### PR DESCRIPTION
**Pull request by fedebonisconti**
Hi,

I have fixed an issue with [another library](https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js) that defines a _exports_ variable in global scope too. It can be useful for another external js libraries that expects to use the same variable at the global scope.

Cheers!

### CODE REVIEW

**Comment by bogdan** [comment]
Sorry, I am a total noob as in backend JS and don't understand the purpose of that `exports` at all. Can you point me an article where it is described? @le0pard maybe you can help?

Your PR breaks the build, please fix it first.

**Comment by le0pard** [comment]
Hello @fedebonisconti . As I know js-routes already using namespace as `Routes` - https://github.com/railsware/js-routes/pull/121#issuecomment-54075048 Why in this case it conflicts with another library? `require` commonjs and `import` from ES2015 is safe for this case.

**Comment by le0pard** [comment]
@fedebonisconti ping

**Comment by le0pard** [comment]
@fedebonisconti ping again

**Comment by le0pard** [comment]
No response. Closing

**Pull request closed without merging**
