### PR TITLE
Support for nested optional parameters (Fix #162)

### LINKED ISSUE #162: Optional parameter discarded
`:action` is only taken into consideration if `:id` is given, see below
```js
Routes.work_assignment_plugin_myprofile_path
"/myprofile(/:profile)/plugin/work_assignment(/:action(/:id))(.:format)"
Routes.work_assignment_plugin_myprofile_path({profile:'gepp', action: 'blah'})
"/myprofile/gepp/plugin/work_assignment"
Routes.work_assignment_plugin_myprofile_path({profile:'gepp', action: 'blah', id: 'oi'})
"/myprofile/gepp/plugin/work_assignment/blah/oi"
Routes.work_assignment_plugin_myprofile_path({profile:'gepp', action: 'blah', id: 'oi', format: 'lah'})
"/myprofile/gepp/plugin/work_assignment/blah/oi.lah"
```

### PR DESCRIPTION
**Pull request by brauliobo**
Issue #162

### CODE REVIEW

**Comment by brauliobo** [comment]
Issue link: #162

**Comment by le0pard** [comment]
cc @bogdan :)

**Comment by brauliobo** [comment]
thanks for this and the 1.1.2 release, already using it on the Gemfile!

**Comment by bogdan** [comment]
np! bugfixes are welcome!

**Pull request merged**
