### PR TITLE
Fix tests for sprockets 3 and depend_on for rails

### PR DESCRIPTION
**Pull request by le0pard**

### CODE REVIEW

**Comment by bogdan** [comment]
What is the reason?

**Comment by le0pard** [comment]
@bogdan current master branch is red on CI, because sprokets-rails >= 3 broken some test cases. Right now I didn't found documentation how to use `depend_on` on version 3 and this can be issue  for this ticket: https://github.com/railsware/js-routes/issues/168 

On this line https://github.com/railsware/js-routes/blob/master/lib/js_routes/engine.rb#L16 for sprockets-rails >= 3 `Rails.application.assets` is `nil`

**Comment by PikachuEXE** [comment]
Maybe take a look at 
https://github.com/fnando/i18n-js/blob/be0691874574655ce57bc75574034cb256ae7111/lib/i18n/js/engine.rb#L23-L36

**Comment by le0pard** [comment]
@PikachuEXE thanks - will check.

**Pull request merged**
