### PR TITLE
Add assign helper

### PR DESCRIPTION
**Pull request by tnandate**
`Object.assign()` does not work with Internet Explorer.
So I would like to add an assign helper to make it work in the same way as `indexOf`.
copied from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

### CODE REVIEW

**Comment by le0pard** [comment]
Nobody care about IE, even Microsoft itself - https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666 . 

If you need support it, use core.js polifils https://alexbogovich.com/blog/core-js/

**Comment by le0pard** [comment]
BTW, it is good idea to cleanup old helpers, which was added only for IE (like `indexOf`). What do you think @bogdan ?

**Comment by bogdan** [comment]
> BTW, it is good idea to cleanup old helpers, which was added only for IE (like indexOf). What do you think @bogdan ?


Agree, I don't think anyone cares now and we should not too.

**Comment by tnandate** [comment]
OK. This pull request will be closed.

**Pull request closed without merging**
