### PR TITLE
Routes.configure(...) at JS level

### PR DESCRIPTION
**Pull request by ksz2k**
Hi

I needed `Routes.set_prefix()` to `defaults['prefix']` be setable based on currently signed in user UID so here's little fix - hoping it'll be usefull for you too.. ;) 

So with this patch we can do the following:

``` javascript
Routes.set_prefix('/ada46feca');

Routes.root_path()
>> '/ada46feca/'
```

### CODE REVIEW

**Comment by Galathius** [comment]
👍

**Comment by le0pard** [comment]
@bogdan looks like we need to close it.

**Comment by bogdan** [comment]
I think not. I keep as a reminder for a good feature that we don't have.

**Comment by bogdan** [comment]
Implemented in master

**Pull request closed without merging**
