### PR TITLE
Test against railties ~> 5.0.0

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by bogdan** [comment]
Build is failing.

**Comment by krzysiek1507** [comment]
It's a bug in rails 5. https://github.com/rails/rails/pull/23235

**Comment by bogdan** [comment]
Let's disable those tests for rails 5.0.0, but enable for everything else expecting 5.0.1 to have the fix.

**Comment by krzysiek1507** [comment]
@bogdan done.

**Comment by bogdan** [comment]
Good job, check the latest version with all the updates!

**Comment by krzysiek1507** [comment]
Thanks!

**Comment by krzysiek1507** [comment]
@bogdan I can't see any new version.

**Comment by bogdan** [comment]
Sorry, fixed: https://rubygems.org/gems/js-routes/versions/1.2.7

**Pull request merged**
